### ISSUE TITLE
Autocorrect-bubble reversed

### ISSUE THREAD

**Issue by senfi** [marty-suzuki/ReverseExtension#26]
I tried something similar a while ago when implementing a messenger-functionality in our app. We came up with the same idea of reverting the tableview and then reverting the cells. So, the cell at the bottom contained a UITextField to enter the text to the other user. A problem we stumbled upon was the autocorrect-bubble: 
![screen shot 2017-05-10 at 08 02 12](https://cloud.githubusercontent.com/assets/806859/25885224/9d75480c-3557-11e7-9340-cc2aeb5d4f25.png)
In this example i just added a textfield to the cell to see what happens… if you type in something and autocorrect comes up with some better stuff, the bubble is reversed. We tried to walk through the view-hierarchy to rotate the bubble, but no solution was satisfying... do you have any idea how to take care of this?

**Comment by marty-suzuki** [comment]
Hi!
I guess that it might be solved this issue to turn off autocorrection with [autocorrectionType](https://developer.apple.com/reference/uikit/uitextinputtraits/1624453-autocorrectiontype).

**Comment by senfi** [comment]
This is "avoided", but not "solved" ;)

**Comment by marty-suzuki** [comment]
> This is "avoided", but not "solved" ;)

It's exactly as you said.

I think UITableViewCell that contains UITextField is not a good UI structure in the first place.
Because UITableViewCell is reusable, it might be changed that's responder.
If you want that, put tapable UILabel to every cell.
When receiving UILabel tap event, calculating UILabel's position from tableView's superview.
Finally, put UITextField to that position.
A UITextFiled appears to be above that UITableViewCell.
